(TeX-add-style-hook
 "Analysis"
 (lambda ()
   (LaTeX-add-labels
    "c:analysis"
    "sec:extremes"
    "tab:rejbounds"
    "sec:impactrace"
    "tab:margrace"
    "fig:racedefmob"
    "eq:vishyp"
    "fig:racedefci"
    "fig:blackdefpol"
    "fig:otherdefpol"
    "fig:whitedefpol"
    "fig:racedefpol"
    "sec:otherfact"
    "fig:racepolit"
    "fig:racegenpol"
    "fig:gengen"
    "sec:mods"
    "eq:fullmod"
    "eq:noraceintmod"
    "eq:novmmod"
    "tab:modcomp"
    "sec:causepro"
    "fig:lawyerexp"
    "sec:casesum"))
 :latex)

